/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class Main {
  public static void main(String[] args) {
    final int x;

    if (true) {
      x = 5;
    }

    System.out.println("x 的值是: " + x);
  }
}
// 运行输出：
// x 的值是: 5
